AllCops:
    TargetRubyVersion: 2.5

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 100
  Severity: warning

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Metrics/ClassLength:
  Severity: warning

Metrics/MethodLength:
  Max: 12
  Severity: warning

Naming/FileName:
  Exclude:
    - 'lib/yle_tf-*.rb'
    - 'spec/yle_tf-*_spec.rb'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 3

Style/NegatedIf:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
